### ISSUE TITLE
ImageMark 可视化 显示text内容

### ISSUE THREAD

**Issue by Xintianbyz** [windzu/wadda#7]
如何利用ImageMark 显示text内容 比如目标类别 Id

**Comment by windzu** [comment]
This is determined by the visualization tool. Tools that support ImageMark visualization, currently I only know that [foxglove](https://github.com/foxglove/studio) supports it, but it does not support displaying text content, I have mentioned related [feature](https: //github.com/foxglove/studio/issues/4413)
